EXP_NAME: viper2city
SOURCE: Viper
DATA_DIRECTORY_SOURCE: ../../data/Viper
DATA_LIST_SOURCE: ../dataset/Viper_list/train.txt
NUM_CLASSES: 15
NUM_WORKERS: 4
TRAIN:
  LEARNING_RATE: 0.0001
  EARLY_STOP: 40000
  LAMBDA_T: 0.1
  SCALING_RATIO:
    - 0.8
    - 1.2
  flow_path_src: ../../../TPSold/data/estimated_optical_flow_viper_train
  DA_METHOD: TPS
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_Viper.json
  INPUT_SIZE_SOURCE:
      - 1280
      - 720
  SNAPSHOT_DIR: ../../experiments/snapshots/viper2city
  SAVE_PRED_EVERY: 1000
TEST:
  SNAPSHOT_DIR: ['../../experiments/snapshots/viper2city']
  MODE: video_best
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_Viper.json
  SNAPSHOT_STEP: 1000
  SNAPSHOT_START_ITER: 1000
